### PR TITLE
Add function to set the initial pose from RVIZ for pure localization mode

### PR DESCRIPTION
**Pull request by tongtybj**
As mentioned in the closed PR #637, manually "tuning" of the robot initial pose from GUI (e.g. Rviz) is a very important function for home service robot, which is supported by the ROS default localization method AMCL.

I hope this PR can facilitate the development of [this RFC](https://github.com/googlecartographer/rfcs/pull/17).

To test my commit, please try following commands
1. First follow the tutorial about  [pure localization](https://google-cartographer-ros.readthedocs.io/en/latest/demos.html#pure-localization) to download rosbags and build the map (.pbstream).
2. Then run following command instead:
```  
$ roslaunch cartographer_ros demo_backpack_2d_localization.launch \
   load_state_filename:=${HOME}/Downloads/b3-2016-04-05-13-54-42.bag.pbstream \
   rosbag:=false
```
3. Use the icon `2D  Pose Estimation` in Rviz to set the initial pose as shown in following image.
Screenshot from 2019-05-12 19-06-45

4. Play the rosbag:
```
$ rosbag play ${HOME}/Downloads/b2-2016-04-27-12-31-41.bag --clock -s 320
```

The whole sequence can be found in [this video](https://drive.google.com/open?id=12B8R-uFGNB9CUBnLMQyslvX1pia1HEJP), and you can also try the 3D mode in this same way.

We have confirmed the 3D performance with our original data, please check [this video](https://drive.google.com/open?id=1lKfQ2_beHCf93W3l0xbGSONjK53sFfTK).

**Limitations**:  the multi-floor map is not supported, since we can not assign the height (i.e. z value) from Rviz.

### CODE REVIEW

**Comment by faizansid77** [comment]
I got the following error while I built your code
```
FAILED: /usr/bin/c++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"cartographer_ros\" -I/home/faizansid/catkin_carto/src/cartographer_ros/cartographer_ros/cartographer_ros/cartographer_ros -isystem /usr/include/lua5.2 -isystem /usr/include/pcl-1.7 -isystem /usr/include/eigen3 -isystem /home/faizansid/catkin_carto/install_isolated/include -isystem /opt/ros/kinetic/include -isystem /opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp -I. -I/home/faizansid/catkin_carto/src/cartographer_ros/cartographer_ros -isystem /usr/include/cairo -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/pixman-1 -isystem /usr/include/freetype2 -isystem /usr/include/libpng12 -isystem /usr/local/include -O3 -DNDEBUG    -pthread -std=c++11 -fPIC  -Wall -Wpedantic -Werror=format-security -Werror=missing-braces -Werror=reorder -Werror=return-type -Werror=switch -Werror=uninitialized -O3 -DNDEBUG -MMD -MT cartographer_ros/CMakeFiles/set_initpose_from_rviz.dir/set_initpose_main.cc.o -MF cartographer_ros/CMakeFiles/set_initpose_from_rviz.dir/set_initpose_main.cc.o.d -o cartographer_ros/CMakeFiles/set_initpose_from_rviz.dir/set_initpose_main.cc.o -c /home/faizansid/catkin_carto/src/cartographer_ros/cartographer_ros/cartographer_ros/set_initpose_main.cc
/home/faizansid/catkin_carto/src/cartographer_ros/cartographer_ros/cartographer_ros/set_initpose_main.cc: In function ‘void move_base_simple_callback(const ConstPtr&)’:
/home/faizansid/catkin_carto/src/cartographer_ros/cartographer_ros/cartographer_ros/set_initpose_main.cc:123:32: error: ‘cartographer_ros_msgs::StartTrajectory::Request {aka struct cartographer_ros_msgs::StartTrajectoryRequest_<std::allocator<void> >}’ has no member named ‘configuration_directory’
   srv_start_trajectory.request.configuration_directory =
                                ^
/home/faizansid/catkin_carto/src/cartographer_ros/cartographer_ros/cartographer_ros/set_initpose_main.cc:125:32: error: ‘cartographer_ros_msgs::StartTrajectory::Request {aka struct cartographer_ros_msgs::StartTrajectoryRequest_<std::allocator<void> >}’ has no member named ‘configuration_basename’
   srv_start_trajectory.request.configuration_basename =
                                ^
/home/faizansid/catkin_carto/src/cartographer_ros/cartographer_ros/cartographer_ros/set_initpose_main.cc:128:32: error: ‘cartographer_ros_msgs::StartTrajectory::Request {aka struct cartographer_ros_msgs::StartTrajectoryRequest_<std::allocator<void> >}’ has no member named ‘relative_to_trajectory_id’
   srv_start_trajectory.request.relative_to_trajectory_id =
                                ^
/home/faizansid/catkin_carto/src/cartographer_ros/cartographer_ros/cartographer_ros/set_initpose_main.cc:130:32: error: ‘cartographer_ros_msgs::StartTrajectory::Request {aka struct cartographer_ros_msgs::StartTrajectoryRequest_<std::allocator<void> >}’ has no member named ‘use_initial_pose’
   srv_start_trajectory.request.use_initial_pose = true;
                                ^
/home/faizansid/catkin_carto/src/cartographer_ros/cartographer_ros/cartographer_ros/set_initpose_main.cc:131:65: error: ‘cartographer_ros_msgs::StartTrajectory::Request {aka struct cartographer_ros_msgs::StartTrajectoryRequest_<std::allocator<void> >}’ has no member named ‘initial_pose’
   tf2::toMsg(relative_initpose_tf, srv_start_trajectory.request.initial_pose);
                                                                 ^
/home/faizansid/catkin_carto/src/cartographer_ros/cartographer_ros/cartographer_ros/set_initpose_main.cc: In function ‘int main(int, char**)’:
/home/faizansid/catkin_carto/src/cartographer_ros/cartographer_ros/cartographer_ros/set_initpose_main.cc:169:18: error: ‘absl’ has not been declared
   map_builder_ = absl::make_unique<cartographer::mapping::MapBuilder>(
                  ^
/home/faizansid/catkin_carto/src/cartographer_ros/cartographer_ros/cartographer_ros/set_initpose_main.cc:169:69: error: expected primary-expression before ‘>’ token
   map_builder_ = absl::make_unique<cartographer::mapping::MapBuilder>(
                                                                     ^

```

**Comment by tongtybj** [comment]
@faizansid77 

 "cartographer_ros_msgs::StartTrajectory" has been changed by #1245 , and `absl::make_unique` is introduced by #955 .

Can you tell me the detail about the build condition?

File: cartographer_ros/cartographer_ros/set_initpose_main.cc [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
+                               itr->data.pose.translation().y(),
+                               itr->data.pose.translation().z());
+
+    // calculate the distance between submap origin and initial pose
+    tf2::Vector3 delta_pos = submap_origin - map_tf.getOrigin();
+    delta_pos.setZ(0);  // only check horinzontal location
+
+    // find the best submap, which is closest to the initial pose
+    // and assign the height (i.e. z value) of this submap to the initial pose
+    if (delta_pos.length() < min_dist) {
```
[the remark this answers is not in the document]
Comment (tongtybj) [reply cartographer_ros/cartographer_ros/set_initpose_main.cc]: I have removed this part (5b09b08daf6a6f1f51296f44e11f8c1f5ba48d40)

File: cartographer_ros/cartographer_ros/set_initpose_main.cc [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+      << "-configuration_directory is missing.";
+
+  // load pbstream
+  ::cartographer::io::ProtoStreamReader reader(FLAGS_load_state_filename);
+  cartographer_ros::NodeOptions node_options;
+  std::tie(node_options, std::ignore) = cartographer_ros::LoadOptions(
+      FLAGS_configuration_directory, FLAGS_configuration_basename);
+  map_builder_ = absl::make_unique<cartographer::mapping::MapBuilder>(
+      node_options.map_builder_options);
+  map_builder_->LoadState(&reader, true);
```
[the remark this answers is not in the document]
Comment (tongtybj) [reply cartographer_ros/cartographer_ros/set_initpose_main.cc]: map build is used to get the frozen trajectory information:
https://github.com/googlecartographer/cartographer_ros/blob/5b09b08daf6a6f1f51296f44e11f8c1f5ba48d40/cartographer_ros/cartographer_ros/set_initpose_main.cc#L109

The trajectory information is required here, since the initial pose of the new trajectory should be provided w.r.t the reference trajectory (i.e. the frozen trajectory). Is it right?

File: cartographer_ros/cartographer_ros/set_initpose_main.cc [hunk 3]
```diff
@@ -0,0 +1,181 @@
...
+              "including files from there.");
+DEFINE_string(configuration_basename, "",
+              "Basename, i.e. not containing any directory prefix, of the "
+              "configuration file.");
+
+DEFINE_string(load_state_filename, "",
+              "Filename of a pbstream to draw a map from.");
+
+namespace {
+int current_trajectory_id_ = 1;
```
[the remark this answers is not in the document]
Comment (tongtybj) [reply cartographer_ros/cartographer_ros/set_initpose_main.cc]: Thank you for the advice. I have revised based on your comment (f0b35a49f35070cf58f232711577715bf62a1e0e)

**Comment by tongtybj** [comment]
@MichaelGrupp  Thank you for your review. I agree that my original implementation is specialized for the 2.5D case. So I improve the code according to your comments.


> Because a minimal initial pose handler can be implemented with a few lines of Python or C++ code using the ROS services /get_trajectory_states, /finish_trajectory and /start_trajectory.

Besides these three services, I think the  information about the reference trajectory (i.e. the frozen trajectory) is also necessary, since the initial pose should be provided w.r.t. the reference trajectory; otherwise, users should covert the transformation by themselves (but common robotics users are tend to use simple gui like rviz):
https://github.com/googlecartographer/cartographer_ros/blob/5b09b08daf6a6f1f51296f44e11f8c1f5ba48d40/cartographer_ros/cartographer_ros/set_initpose_main.cc#L109-L124

BTW, calling `/finish_trajectory` can stop an ongoing trajectory building, but the map would remain. This effects the navigation performance (e.g. move_base) based on  the `/map` topic published by `cartographer_occupancy_grid_node`. So I think there should be a service to delete the unnecessary trajectory, or is there already some solution?

**Comment by wesigj** [comment]
@tongtybj 
have you finish this issue, i want to use 'Add function to set the initial pose from RVIZ for pure localization mode ' this function  in my cartographer,but i don't know how to use your function, could you help me?
Thank you for your contributions

**Comment by greymfm** [comment]
Maybe it's more elegant to do the rviz initial pose feature 'outside' Cartographer via a simple Python script? At least that's how I did it :-) https://github.com/cartographer-project/cartographer_ros/issues/1652
